print ("What is your name?")
yourName = input()
print ("How old are you?")
yourage = input()
print ("Where do you live?")
youlive = input()
print ("Hello! ", yourName)
print ("Your age :", yourage )
print ("You live in" , youlive)
print ("Thank you!")